### ISSUE TITLE
inverted text with dark background

### ISSUE THREAD

**Issue by nervusvagus** [greiman/SSD1306Ascii#10]
Hello,
For some sensor values above or below the expected value, I use the oled display to show these out of bound values in dark background and light text.

is there any way to do this in SSD1306Ascii?

**Comment by greiman** [comment]
There is no way in this library to invert text pixels.

I think you could use the openGLCD library.  openGLCD has a feature to invert pixels in a rectangle.

If I wanted this feature with my library, I would construct a special font for numbers with inverted pixels.
