### ISSUE TITLE
Font Length wrong conversion?

### ISSUE THREAD

**Issue by eos1d3** [greiman/SSD1306Ascii#11]
From allFonts.h, " FONT_LENGTH is a 16 bit Big Endian length field."

But in SSD1306Ascii.cpp:

`size_t SSD1306Ascii::write(uint8_t ch) {
  const uint8_t* base = m_font;
  if (!base) return 0;
  uint16_t size = readFontByte(base++) << 4;
  size |= readFontByte(base++);
`

I think 4 is not right. Should it be

`uint16_t size = readFontByte(base++) << 8;`

**Comment by greiman** [comment]
The size field is now meaningless as a number.  You just need to make sure the first byte is zero in this test.
````
  if (size < 2) {
````
A better test would be like this from openGLCD

````
#define isFixedWidthFont(font)  ((FontRead(font+FONT_LENGTH) == 0) && (FontRead(font+FONT_LENGTH+1) < 2))
````

I will change the test in the next version since it is confusing but should always work.
