### ISSUE TITLE
Display is messed up

### ISSUE THREAD

**Issue by fitaine** [greiman/SSD1306Ascii#122]
Hello, help wanted here please :)

I'm trying to build a [Servo operated 3D Printed Shutter for Arduino Nano](https://github.com/hackaninstant/Servo-Shutter) and I'm having trouble with the display when I use SSD1306Ascii.

My script wouldn't work so I tried to load the examples but non worked. Then, I tried to load examples from Adafruit SSD1306 library to know if the problem come from the OLED screen and it runs smoothly.

Here is the symptom: Display seems to be not aligned
1 - Wire 128x64 example 
![Wire 128x64](https://github.com/user-attachments/assets/6369d4bd-7562-4b6d-8745-ce74e4d03458)

2 - HelloWorldWire 128x64. I just get the last character of the oled.print ( here the exclamation mark) on the top left corner
![IMAGE 2024-09-15 11:50:04](https://github.com/user-attachments/assets/929b1bd0-055e-44e0-acfb-8343ed8d28fb)

3 - ssd1306_128x64_i2c (Adafruit SSD 1306 example)
![IMAGE 2024-09-15 11:52:56](https://github.com/user-attachments/assets/bdd3f84e-db18-4f73-b3f1-68138760b71d)

The components I use are Arduino Nano and Oled screen 1306 from Aliexpress [link to product page](https://fr.aliexpress.com/item/32643950109.html?spm=a2g0o.order_list.order_list_main.75.6b835e5bheGidR&gatewayAdapt=glo2fra)

do you have any idea what I did wrong here ? Can you help me sorting it out please ?

**Comment by greiman** [comment]
Looks like the display controller for this module is a 12864.  It claims to be 1306 compatible but I must use some command that is not handled by the 12864.

I am only doing minimal maintenance on this library so don't plan to add features or support new controllers.

**Comment by fitaine** [comment]
Ok, so it might be a hardware compatibility after all. I've checked different product pages and I don't find the display controller info on it.
Would you mind pointing a 128x64 oled screen that would be compatible ?

Anyway, thanks for the clarification and the help ! I'm gonna buy an other one and try if it works better.

**Comment by greiman** [comment]
> Would you mind pointing a 128x64 oled screen that would be compatible ?

I really can't help.  I developed this library nine years ago and it has been about five years since I bought an oled.  The ones I bought from Adafruit are now discontinued.
