### ISSUE TITLE
rest method

### ISSUE THREAD

**Issue by eos1d3** [greiman/SSD1306Ascii#14]
This is a suggestion only.

Do you consider to move **reset** method out of SD1306Ascii.cpp.

This is hardware/mcu dependence. Once it is moved out, the whole cpp can be used by any other platform. I have ported it to STM8 already. The only change is the reset method (and a little to SPI class). 

Without moving it out, you will need to include mcu header files inside. So I moved it out. Then the rest of the codes complied fine.

I moved it via a virtual to SPI class. So only SPI file has mcu dedicated headers while SD1306Ascii.cpp is so clean and works with any platform.

**Comment by greiman** [comment]
Currently I have little interest in developing this library for other than Arduino boards.  I just don't have time for all the projects I am involved with.

In fact I am not using Arduino much for my personal projects.  I mostly develop with Cortex-M boards and I like  the ChibiOS/RT RTOS system.
