### ISSUE TITLE
ESP8266: #warning set400kHz() disabled for this CPU

### ISSUE THREAD

**Issue by Anton-V-K** [greiman/SSD1306Ascii#15]
The library issues warning
```
src/SSD1306AsciiWire.h:61:2: warning: #warning set400kHz() disabled for this CPU. [-Wcpp]
```
when compiling `SSD1306AsciiWire.h` for ESP8266 (NodeMCU 1.0) with Arduino IDE 1.6.9.

**Comment by greiman** [comment]
You must replace the warning with code for ESP8266.

**Comment by Anton-V-K** [comment]
Same as #5

**Comment by greiman** [comment]
The warning will be removed from a future update.  Also set400kHz() will be removed.

Most versions of wire now have this call to set the I2C clock.

` Wire.setClock(400000L);`
