### ISSUE TITLE
Adding library

### ISSUE THREAD

**Issue by smadds** [greiman/SSD1306Ascii#18]
Real newbie question...

How do I install your library into the Arduino IDE? I have tried downloading as Zip, then in IDE: Sketch/Include Library/Add .ZIP library but the IDE complains it's not a valid library zip

**Comment by greiman** [comment]
This

**Comment by greiman** [comment]
This library still needs manual installation.   See the manual installation section [here](https://www.arduino.cc/en/Guide/Libraries).

I will update to the library manager in the future.
