### ISSUE TITLE
small reorganization of files

### ISSUE THREAD

**Issue by robertoostenveld** [greiman/SSD1306Ascii#19]
Thanks for this great library.

Could you consider reorganizing the code such that "src", "examples" and "library.properties" appear at the top level directory, rather than in the SSD1306Ascii/SSD1306Ascii subdirectory? 

That allows to install it like this

```
cd ~/Arduino/library
git clone https://github.com/greiman/SSD1306Ascii.git
```

after which it is immediately detected as library and the examples can be selected from the example menu.

best regards,
Robert

**Comment by greiman** [comment]
I plan to restructure all my libraries for the Arduino Library manager.  It will happen with the next mod of each of my libraries.

They will all be like [DigitalIO](https://github.com/greiman/DigitalIO).

**Comment by greiman** [comment]
done
