### ISSUE TITLE
Use with rtc ds3231

### ISSUE THREAD

**Issue by boyswat** [greiman/SSD1306Ascii#25]
Hi. I using ur library, very good. But i have problem when use ds3231 rtc module. I use i2c oled and ds3231 use sda and scl like oled. Oled will not work if i using ds3231 at same time. Can you help me use both? Sr my english very bad. Thank you.

**Comment by boyswat** [comment]
Ds3231 library i using
http://www.rinkydinkelectronics.com/library.php?id=73

**Comment by DirtyEngineer** [comment]
My guess is that your oled module and rtc module are using the same I2c address. You can use this sketch (http://playground.arduino.cc/Main/I2cScanner) to scan the addresses of the oled and ds3231 to check. The ds3231 uses address 0x68 address.

**Comment by greiman** [comment]
I can't help you solve I2C device conflict problems.

**Comment by boyswat** [comment]
I change other library ds3231 and it work. Sr for reply too late.
