### ISSUE TITLE
Restructure folder layout for Add .zip library in arduino

### ISSUE THREAD

**Issue by jared0x90** [greiman/SSD1306Ascii#30]
Hey there, I love this little i2c OLED library along with Arduiniana's Streaming5. One thought to improve it for future uses is to move the actual project folder one level higher (make the SSD1306Ascii subfolder the top level folder) . As it stands I can download this repo as a zip, take out the "SSD1306Ascii" subfolder, then zip that back up and then install it as a zip plugin library in Arduino. As this project has no tagged releases otherwise, I think making this change would let people drop it into the Arduino IDE more easily.

**Comment by greiman** [comment]
I plan to restructure it for the library manager soon.  First I need to test several mods for handling reset for I2C displays.

**Comment by jared0x90** [comment]
Ah OK, it hasn't been touched in a while so I thought it might be being left as is going forward. I forked it and made it compatible so I could reference it in my own source. Feel free to take a look or I can shoot your a PR if you have any interest.
