### ISSUE TITLE
ESP32 WEMOS Lolin32 embedded OLED 128x64

### ISSUE THREAD

**Issue by makbas** [greiman/SSD1306Ascii#39]
Hi,
I cannot make it work it with ESP32 WEMOS Lolin32 embedded OLED 128x64 module.
My guess is the I2C pins are different on this board. 

How can we enforce it to use specific pins for I2C?

**Comment by greiman** [comment]
See [this](https://github.com/greiman/SSD1306Ascii/issues/37#issuecomment-384671840).

You will need to determine pins for your board.  You may want to modify code to use the second I2C controller.

**Comment by makbas** [comment]
OK, thank you.
I knew that the I2C pins on this board are pin5 (SDA) and pin4 (SCL).

Wire.begin(5, 4);    // did the trick :)

Thanks a lot.
