### ISSUE TITLE
Suggestion : Update README with ESP8266 support

### ISSUE THREAD

**Issue by gerardwr** [greiman/SSD1306Ascii#4]
Hi,

I uploaded the example sketch "HelloWorldWire" to an ESP8266 board (actually a Wemos D1) and it runs without any changes :-)

Maybe something for the README?

Thanks.

**Comment by greiman** [comment]
That's interesting.  It runs on quite a few Arduino-like boards.

I will add a comment to the README.

**Comment by gerardwr** [comment]
I have used the library on an Arduino Uno and on the Wemos D1 ESP8266 board.

Permitting time, I will try to run it on an Attiny85, then all my platforms are covered :-).
