### ISSUE TITLE
SSD1306 flashes on and off on waking from deepsleep . Any workaround ?

### ISSUE THREAD

**Issue by SrikanthBala** [greiman/SSD1306Ascii#54]
I am using a ESP32 Dev Module and the 128x64 I2C SSD1306 using your library. My program needs to deepsleep and wake up twice every second. On every wake the SSD is sent  a screen reset and so my display blinks twice every second. Not very pleasant

Can I do something to stop that ?

Thanks

**Comment by greiman** [comment]
The library only does a reset for a I2C display if you call begin() and the display has a reset pin.

Reset for an I2C display with a reset pin happens when the reset pin is toggled low for at least 10 ms.

Reset on an I2C display with 4 pins is done by hardware when voltage is applied, there is no software reset.

**Comment by SrikanthBala** [comment]
Thank you for your prompt reply. I could not get around to look into it being busy at work. 
My I2C SSD1306 has no reset pin. So it must be doing it only on power on.
I had already tried to check whether the ESP32 was waking up from sleep or from reset and not issuing a begin command when it was waking up from sleep. But then the display just freezes and doesnt update any changes 
So my clock stops after the first wake up and only updates once after a hardware reset or power cycling and then freezes again.
Using begin() works but with that blinking effect.
Any ideas ?

**Comment by greiman** [comment]
I can't help since I don't have your hardware.

If power is lost on the display, you must call oled.begin().

A long shot is to just call Wire.begin() but not oled.begin().
