### ISSUE TITLE
QUESTION:"refresh rate"

### ISSUE THREAD

**Issue by skovacijer** [greiman/SSD1306Ascii#6]
Is it possible to have only one line refreshing instead of whole screen?

I have data coming from a sensor, there are few lines displayed on screen which dont need to be refreshed(text) , but data from sensor should be updated every time it changes. So is there a way to make just one "line" refresh or to smooth out the refreshing (of the whole screen) or make it faster?

Thanks

P.S. I have just started arduino and you made a great library for oled, thank you once again

**Comment by greiman** [comment]
You can position the cursor to the field that needs to be updated and only write the new value.
```
  /**
   * @brief Set the cursor position.
   *
   * @param[in] col The column number in pixels.
   * @param[in] row the row number in eight pixel rows.
   */
  void setCursor(uint8_t col, uint8_t row);
```
