### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by hawkagent** [greiman/SSD1306Ascii#7]
Hello,

I've been looking for a debugging solution for my arduino mega without connecting it to my laptop for Serial, and I came across this wonderful library! It was an easy setup to display text on my tiny oled screen. I know it's still in development, so here are some features I'd love to see some day:

- When printing a long line, instead of truncating, break it down and print in multiple lines
-  Rotate screen. If it would helpful to use the screen as 64x128 instead of 128x64

Despite my limited programming knowledge, I will try to figure this out and post it here. Thanks for the library!

**Comment by greiman** [comment]
You can easily make a wrapper class that breaks long lines.  You could also write a simple function that breaks long lines.

Rotating the screen is very difficult without a internal RAM buffer.  The purpose of this library is a very lightweight ASCII library.

If you need a rotated screen, use a different library that has an internal RAM buffer  This library may have rotated text. [https://github.com/olikraus/u8glib](url)
