### ISSUE TITLE
Verdana_digits_24

### ISSUE THREAD

**Issue by koendv** [greiman/SSD1306Ascii#81]
Hi. Thanks for a library that is small and works. I'm using your library on STM32. 
A request: the font "Verdana_digits_24", extended with the characters '-' and '.', so a float can be printed. This would add 3 characters to the font.
Thank you.

**Comment by greiman** [comment]
I was only able to find Verdana_digits_24. This font was created by Fabien Maximilian Thiele but that was many years ago and I can't find the full font.  Many graphics libraries have  Verdana_digits_24.
