### ISSUE TITLE
[not a issue] request for changes directory structure

### ISSUE THREAD

**Issue by reaper7** [greiman/SSD1306Ascii#9]
It is possible to change directory structure of this lib?
I usually use a raw version of my favorite libraries from github repository
but it requires suitable for arduino ide directory structure,

so, target library must be inside main dir (not inside subdir)

please look at my fork Your library, with revised structure:
https://github.com/reaper7/SSD1306Ascii

Can you apply such a structure?

If yes, then I can put pull request

**Comment by greiman** [comment]
I will be changing the structure of this and other libraries in the future.  I need a uniform way to support several systems besides Arduino.
